### ISSUE TITLE
bug: Unnecessary dependency to Python 3.10

### ISSUE THREAD

**Issue by Algue-Rythme** [JaxGaussianProcesses/GPJax#155]
# Bug Report

**GPJax version: 0.5.2**

PR #154 

**Current behavior:**

The code of JaxLinop uses the line `from functools import cache` ( https://github.com/JaxGaussianProcesses/JaxLinOp/blob/c1c372e3f142cc6d78d52114537588c4a52e3b27/jaxlinop/linear_operator.py#L19 ). Unfortunately this is not available in Python 3.8 (and below). I used to have code running on Colab depending on GPJax, and now in the middle of a rebutall for a conference the code does not work anymore because of the dependency broken. 

Being forced to use the latest version of Pytpn is a strong requirement. Furthermore the `cache` decorator is currently not used.

By the way, this is a great library, keep up with the good work I love it!

**Comment by Daniel-Dodd** [comment]
Hi @Algue-Rythme, Thanks for spotting. This import is a mistake. Feel free to open a PR to `JaxLinOp` and I will approve, (or I will fix this later this weekend). :)

**Comment by thomaspinder** [comment]
Hi @Algue-Rythme - JaxLinOp and GPJax have now been bumped. Please install gpjax==0.5.3 and it should be compatible with Colab again. Best of luck with the rebuttal.
