### ISSUE TITLE
docs: Add triangular solve figure

### ISSUE THREAD

**Issue by thomaspinder** [JaxGaussianProcesses/GPJax#268]
In our sharp bits doc, we acknowledge that solving a system of equations using the Cholesky factor is faster than using the dense covariance matrix. It would be nice to have a figure that depicts why this is true.

**Comment by Yash5675** [comment]
Hi, this is my first issue but I am really interested in it. How can I apply for it.

**Comment by thomaspinder** [comment]
Hi @Yash5675, thanks for the interest. For [this section in our sharp bits doc](https://docs.jaxgaussianprocesses.com/sharp_bits/#why-is-positive-definiteness-important), it would be nice to have an example of solving a small (3x3) system of equations using Cholesky factors. 

If I have a PSD matrix $A=LL^{\top}$ and I want to solve $Ax=y$, then I can first solve $Lx=b$ and then $L^{\top}x=b$. These two operations both involve triangular matrices and are, therefore, faster than brute force solving $Ax=y$. If this is new to you, then there are some nice details on this in [Chapter 26 of Numerical linear algebra](https://cdn.bc-pf.org/resources/math/algebra/linear_algebra/Trefethen_Bau-Numerical_Linear_Algebra.pdf). 

It would be nice to have something that elucidates this idea. Ideally, this would be a figure, but also a toy math example would be fine too. You can include this into the sharp bits doc and open a PR. If you have any questions, then please don't hesitate to message. We do also have a Slack channel.

**Comment by Yash5675** [comment]
@thomaspinder thank you for the great explanation and materials for more information. I have some questions. Shall I ask them here or on slack? I am fine with either.

**Comment by thomaspinder** [comment]
Wherever you prefer. If your questions are package-specific, then posting here may be better for transparency. Otherwise, Slack is fine :)

**Comment by Yash5675** [comment]
Ok, I will just ask them here. So, what I have to do is add an illustration into  `docs/sharp_bits.md` at the end of the Positive-definiteness section. _Please correct me if I am wrong._ 
About the illustration, it should show Cholesky factorisation steps: 
1. Cholesky Decomposition 
2. Forward Substitution 
3. Backward Substitution 

through an example of 3x3 system of equations? (should I also include the operation count?).
And ideally it should be a figure (should I add the figure into the `docs/_static/` and use the link from there?). 

_PS: I have no idea what I am saying. Please correct me if any of the information is wrong or needs more improvement._

**Comment by thomaspinder** [comment]
Correct. If you are able to include the operation count, then that would be excellent! A figure would be ideal and yes, it can go under `docs/_static/` for now. 

Feel free to exercise your creativity here - if, whilst doing this, you feel there's a better way to illustrate the point, then you should free to do this. We can manage any imperfections or areas for improvement through the PR.

**Comment by Yash5675** [comment]
Sorry for the late reply. I have opened a PR. Please let me know what changes I need to make. Thank you very much.
