### ISSUE TITLE
docs: Introduction to kernels

### ISSUE THREAD

**Issue by thomaspinder** [JaxGaussianProcesses/GPJax#269]
Similar to our notebook on an [introduction to Gaussian processes](https://docs.jaxgaussianprocesses.com/), it would be good to have a notebook that introduces kernel functions to individuals new to GPs.

**Comment by Thomas-Christie** [comment]
Will work on this.

**Comment by kunjshukla** [comment]
hey, I would like to contribute to this issue. Please assign this to me.

**Comment by thomaspinder** [comment]
Thanks @Thomas-Christie and @kunjshukla. Yes, the notebook should focus more on the mathematics of kernels and explain concepts like Gram matrices, positive-definite.etc
