### ISSUE TITLE
feat: PyTree representation

### ISSUE THREAD

**Issue by thomaspinder** [JaxGaussianProcesses/GPJax#272]
# Feature Request

It would be helpful for users if we could print out the PyTree's current state to the terminal This is similar to what [PyTreeClass](https://github.com/ASEM000/PyTreeClass) does, but we would need to include information about the parameters' value, bijector, and trainability status.

It would be nice to have something similar to Flax where our `Module` has a `display` or `tabulate` method that prints the PyTree's state.

**Additional Context**

[Flax example](https://flax.readthedocs.io/en/latest/api_reference/_autosummary/flax.linen.tabulate.html#flax.linen.tabulate)
[PyTreeClass](https://github.com/ASEM000/PyTreeClass/blob/main/pytreeclass/_src/tree_pprint.py)

**Comment by ASEM000** [comment]
Hello there, 

`pytreeclass.tree_summary` should work out of the box with registered pytrees, I think you can achieve your objective with the following pattern.

```python

import pytreeclass as pytc
import jax
import gpjax as gpx
kernel = gpx.kernels.RBF()

print(pytc.tree_summary(kernel))
# ┌────────────┬─────┬─────┬─────┐
# │Name        │Type │Count│Size │
# ├────────────┼─────┼─────┼─────┤
# │.lengthscale│f32[]│1    │4.00B│
# ├────────────┼─────┼─────┼─────┤
# │.variance   │f32[]│1    │4.00B│
# ├────────────┼─────┼─────┼─────┤
# │Σ           │RBF  │2    │8.00B│
# └────────────┴─────┴─────┴─────┘


# use `is_leaf` to contol the display

print(pytc.tree_summary(kernel, is_leaf=lambda x: isinstance(x, gpx.AbstractKernel)))
# ┌────┬────┬─────┬─────┐
# │Name│Type│Count│Size │
# ├────┼────┼─────┼─────┤
# │Σ   │RBF │2    │8.00B│
# └────┴────┴─────┴─────┘

# use dispatching to customise the display of RBF in `tree_summary`
@pytc.tree_summary.def_type(gpx.kernels.RBF)
def _(node:gpx.kernels.RBF) -> str :
    return f"Some useful info about RBF"


print(pytc.tree_summary(kernel, is_leaf= lambda x: isinstance(x, gpx.AbstractKernel)))
# ┌────┬──────────────────────────┬─────┬─────┐
# │Name│Type                      │Count│Size │
# ├────┼──────────────────────────┼─────┼─────┤
# │Σ   │Some useful info about RBF│2    │8.00B│
# └────┴──────────────────────────┴─────┴─────┘
```

Let me know if this helps.
