### ISSUE TITLE
feat: Attach priors to parameters

### ISSUE THREAD

**Issue by thomaspinder** [JaxGaussianProcesses/GPJax#273]
# Feature Request

We currently have no ability to assign a prior distribution to a parameter. This is limiting for users wishing to construct _fully_ Bayesian GPs. Similar to how a user can specify the trainability of bijector of a parameter, they should be able to provide the prior distribution.

**Describe Preferred Solution**

Mimic the functionality used to supply and update bijectors for prior distribution. The distribution should be from TensorFlow probability.

**Comment by Thomas-Christie** [comment]
Will we be wanting to enable users to specify whether their prior is over the *constrained* or *unconstrained* parameters, or just force users to place the prior over the *constrained* parameters? For instance, I believe GPFlow supports the former option (https://github.com/GPflow/GPflow/blob/develop/gpflow/base.py#L118). Depending on how this gets implemented, I think it's likely that being able to tell whether a parameter is in a constrained or unconstrained state (#274) will also be useful.
