### ISSUE TITLE
dev: ensure correct PyTest/PyTest dependencies install

### ISSUE THREAD

**Issue by ingmarschuster** [JaxGaussianProcesses/GPJax#292]
`pytest tests --cov=./ --cov-report=html`  (or a simple `pytest tests`)  results in `AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'` , an error that originates in `File “/opt/homebrew/Caskroom/miniforge/base/envs/pe/bin/pytest”, line 8, in <module>
    sys.exit(console_main())` which probably means that we have to make sure the correct pytest/pytest dependencies are installed by poetry

**Comment by thomaspinder** [comment]
I find this perplexing. We have relatively strict minimum versions for pytest specified in our pyproject.toml file - https://github.com/JaxGaussianProcesses/GPJax/blob/main/pyproject.toml#L29.

Can I check that you ran `poetry install --with tests` when install the dependencies?

**Comment by ingmarschuster** [comment]
On the main branch? This gives me, in a fresh environment:
```
GPJax-main % poetry install --with tests

Group(s) not found: tests (via --with)```.

I can still do `poetry install` . The fresh environment seems to help with `pytest tests --cov=./ --cov-report=html`. I checked the versions, and urllib3 installed in the fresh environment is the same version as in the old environment (in which the error  persists). This makes it sound like a hard-to-track version error. I'll close this, and just make a new environment.
In case somebody else has the problem, they can re-open.
