### ISSUE TITLE
bug: Overly restrictive jaxlib dependency?

### ISSUE THREAD

**Issue by james-bowden** [JaxGaussianProcesses/GPJax#336]
# Bug Report

**GPJax version:** 0.6.6

**Current behavior:**

Jaxlib dependency (==0.4.7) seems overly restrictive, believe it comes from [this line](https://github.com/JaxGaussianProcesses/GPJax/blob/ce4090477fd11dde0403351e97a3f37a450faf00/poetry.lock#L959). 
I have used GPJax with jaxlib==0.4.12 (just brute force installed jax version after GPJax was already installed) and basic GP operations still work, as far as I can tell. Not exhaustively tested, and definitely could be the case that newer jaxlib version breaks some part of the package that I'm not using.

Would like to work with newer versions of jaxlib--particularly relevant for using on GPU, where need newer versions of jaxlib to correspond to newer versions of nvidia CUDA already installed on my server (or face manual jax installation?). I can overwrite and get to work, but a bit frustrating for sharing environments including GPJax through yaml or requirements.txt, etc. where cannot specify a sequential install to override GPJax's current dependency. Not a huge issue, but if easy fix would be nice :)

**Comment by thomaspinder** [comment]
Hi @james-bowden - you're correct in flagging this as an issue. It comes from an early issue with JAX [see here](https://github.com/google/jax/issues/15951). Would you be willing to open a PR to remove this pin? It'd involve editing the `pyproject.toml` file and then updating the Poetry lockfile.

**Comment by Thomas-Christie** [comment]
Fixed in https://github.com/JaxGaussianProcesses/GPJax/pull/366.
