### ISSUE TITLE
bug: discrepancy in usage of Gaussian likelihood's `obs_noise` (std. dev. and variance)

### ISSUE THREAD

**Issue by etienne-thuillier** [JaxGaussianProcesses/GPJax#399]
# Bug Report

Hi,

I think I found an inconsistency in the code base (see below), which, if confirmed could be very consequential.

In any case, documentation is lacking and a simple clarification on this matter should be added into the header of  the `Gaussian` class.

With thanks!

**GPJax version:**
v0.7.0

3f85263

**Current behavior:**
On one hand `obs_noise` corresponds to standard deviation in `Gaussian` class from [likelihoods.py](https://github.com/JaxGaussianProcesses/GPJax/blob/main/gpjax/likelihoods.py):
`return tfd.Normal(loc=f, scale=self.obs_noise.astype(f.dtype))`

Indeed, the `scale` argument is indeed the standard deviation, cf. [tfp.distributions.Normal].(https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Normal).

On the other hand `obs_noise` corresponds to variance, e.g. in `ConjugatePosterior` class from [gps.py](https://github.com/JaxGaussianProcesses/GPJax/blob/main/gpjax/gps.py):
` # Observation noise o²`
`obs_noise = self.likelihood.obs_noise`
and further down
`# Σ = Kxx + Io²`
`Sigma = cola.ops.Kronecker(Kxx, Kyy)`
`Sigma += cola.ops.I_like(Sigma) * (obs_noise + self.jitter)`

**Expected behavior:**
Code should be consistent.

Furthermore, there should be a definition of `obs_noise` in the heade of `Gaussian` class from [likelihoods.py](https://github.com/JaxGaussianProcesses/GPJax/blob/main/gpjax/likelihoods.py), but it is lacking and so the user is left wondering or searching through the code (which caused me to find this potential discrepancy).

**Comment by daniel-dodd** [comment]
Thanks for spotting this @etienne-thuillier. This is certainly a bug, and moreover, `obs_noise` is not a good name - easy to make a mistake. We have opened a PR to resolve this #400, and will release a new version of GPJax soon after this is merged.

**Comment by thomaspinder** [comment]
Thanks for flagging this @etienne-thuillier. This has now been resolved in [v0.7.1](https://github.com/JaxGaussianProcesses/GPJax/releases/tag/v0.7.1).
