### ISSUE TITLE
docs: Very minor correction

### ISSUE THREAD

**Issue by neel-maniar** [JaxGaussianProcesses/GPJax#431]
A very minor correction to the `docs/examples/intro-to-gps.py` document. (It is a great introduction to GPs, thank you for including it!)

In line 406, it says $\mathbf{X}\in\mathbf{X}$ whereas it should say $\mathbf{X}\in\mathcal{X}$.

**Comment by st--** [comment]
Hi @neel-maniar, thanks for noticing! would you be up for making the change yourself directly and preparing a pull request? :)

**Comment by neel-maniar** [comment]
Hi @st--, thanks for your prompt reply! I am a bit new to GitHub, but have attempted to make a pull request. Hopefully it works as expected!

**Comment by thomaspinder** [comment]
Resolved in #433
