### ISSUE TITLE
docs: Missing Dependency: "jaxopt" Not Listed in gpjax Documentation

### ISSUE THREAD

**Issue by LiHao-MS** [JaxGaussianProcesses/GPJax#444]
When attempting to use “gpjax” by importing the fit function via “from gpjax.fit import fit”, an ImportError occurs if jaxopt is not installed: cannot import name 'ScipyBoundedMinimize' from 'jaxopt' (unknown location). However, jaxopt is not listed in the requirements for gpjax. This issue traces back to ./gpjax/decision_making/utility_maximizer.py, specifically at line 23: from jaxopt import ScipyBoundedMinimize.

Considering that “jaxopt” has transitioned to maintenance mode and its functionalities are being integrated into “Optax”, it might be advantageous to replace all code dependencies on “jaxopt” with their “Optax” counterparts. This shift could significantly improve the future compatibility and maintainability of "gpjax".

**Comment by thomaspinder** [comment]
Thanks for raising this. Fixed now in [v0.8.2](https://github.com/JaxGaussianProcesses/GPJax/releases/tag/v0.8.2).
